#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER postgres WITH PASSWORD NULL;
	GRANT ALL PRIVILEGES ON DATABASE "$POSTGRES_DB" TO postgres;
	GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO postgres;
EOSQL
