FROM python:3.10

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV FLASK_APP run.py
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_DEBUG=0

WORKDIR /var/www/

# install python dependencies
COPY ./requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt


COPY ./ .
RUN pip install alerta

WORKDIR /var/www/rps_admin_interface
COPY ./config.yaml .

EXPOSE {{app_port}}

CMD [ "python3", "-m" , "flask", "run", "-p", "{{app_port}}"]