# syntax=docker/dockerfile:1
FROM python:3.8
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
# temp: placing the config file in the container
WORKDIR /etc
RUN mkdir rps-admin-web-interface
COPY rps-admin-tools.json /etc/rps-admin-web-interface/rps-admin-tools.json

WORKDIR /code
COPY . /code/
RUN echo "psycopg2==2.8.6" >> requirements.txt
RUN pip install -r requirements.txt
RUN pip install psycopg2-binary