FROM python:3.10

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV FLASK_APP app.py
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_PORT={{app_port}}

WORKDIR /var/www/

# install python dependencies
COPY ./rps_profile_interface ./rps_profile_interface
WORKDIR /var/www/rps_profile_interface
COPY config.yaml .

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt


EXPOSE {{app_port}}
CMD [ "python3", "-m" , "flask", "run", "-p", "{{app_port}}", "--debug"]
